version: 0.2

env:
  secrets-manager:
    ETL_PROJECT_ACCESS_KEY_ID: "arn:aws:secretsmanager:us-east-1:690469543125:secret:etl-project-access-key-id-eUT3Wr"
    ETL_PROJECT_SECRET_ACCESS_KEY: "arn:aws:secretsmanager:us-east-1:690469543125:secret:etl-project-secret-access-key-km3iyd"

phases:
  pre_build:
    commands:
      - echo "Executing pre-build commands"
      - set -e
      # - COMMIT=$(git rev-parse HEAD)
      # - TAG=$(git describe --exact-match --tags $COMMIT 2>/dev/null || echo "none")

      # - if [ "$TAG" == "none" ]; then
      #     echo "No tag found. Exiting build.";
      #     exit 1;
      #   fi

  build:
    commands:
      - echo "Build commands"
      - echo "# AWS Configuration" > env.py
      - echo "AWS_ACCESS_KEY_ID=\"$ETL_PROJECT_ACCESS_KEY_ID\"" >> env.py
      - echo "AWS_SECRET_ACCESS_KEY=\"$ETL_PROJECT_SECRET_ACCESS_KEY\"" >> env.py
      - echo "Executing build commands"
      - chmod +x ./push_to_ecr.sh
      - ./push_to_ecr.sh --container-service "docker"

post_build:
  commands:
    - echo "Executing post-build commands"
