version: 0.2

phases:
  pre_build:
    commands:
      - echo "** Executing pre-build commands **"
      - echo "# AWS Configuration" > env.py
      - echo "AWS_ACCESS_KEY_ID=\"$AWS_ACCESS_KEY_ID\"" >> env.py
      - echo "AWS_SECRET_ACCESS_KEY=\"$AWS_SECRET_ACCESS_KEY\"" >> env.py

  build:
    commands:
      - echo "** Executing build commands **"
      - chmod +x ./push_to_ecr.sh
      - ./push_to_ecr.sh --container-service "docker"

post_build:
  commands:
    - echo "** Executing post-build commands **"